#!/usr/bin/python3

def play_round(player1_move, player2_move):
    payoff_matrix = {
            ('C', 'C'): (3, 3),
            ('C', 'D'): (0, 5),
            ('D', 'D'): (1, 1),
            ('D', 'C'): (5, 0)
                }
    score = payoff_matrix[player1_move, player2_move]
    player1_score = score[0]
    player2_score = score[1]
    return player1_score, player2_score

def strategy_always_defect():
    return 'D'

def strategy_always_cooperate():
    return 'C'

i = 1
total_score_1 = 0
total_score_2 = 0
for i in range(100):
    score = play_round(strategy_always_defect(), strategy_always_cooperate())
    total_score_1 += score[0]
    total_score_2 += score[1] # 善人の破滅を見よ

print({total_score_1}, {total_score_2})
